### ISSUE TITLE
Add lesson on creating repos using GitHub

### ISSUE THREAD

**Issue by iAmWillShepherd** [codeparkhouston/GitHub-Workshop#1]

**Comment by wnjnz** [comment]
**How to add repos:**
- github desktop - only creates local repository
- github.com - lives on github.com, pull locally.

**explain key difference: what's local and what's online and what does that entail**

**Comment by iAmWillShepherd** [comment]
We can use the [documentation](https://guides.github.com/) that GitHub has already produced.
